### ISSUE TITLE
Not Correctly adding NS record to a MX Query with DNSSEC

### ISSUE THREAD

**Issue by wwhitecar** [MSU-CS4360-JDNS/JDNSS#44]

**Comment by cblanto7** [comment]
I think that could have something to do with the `addRRSignature()` method in Response.java

**Comment by cblanto7** [comment]
after look it at if for a bit, I think the issue is within `addAuthorities()` 
specifically, `if (!UDP || responses.length + authority.length < maximumPayload)`.
I traced both values 
`responses.length` + `authority.length` = 748
`maximumPayload` = 512

so the authorites are not being added because it would exceed current maximum payload size.

So it seemed that we need to indicate truncation, so that we can repeat the query over TCP...

```
else if(responses.length + authority.length >= maximumPayload){
   header.setTC(true);
}
```
